### PR TITLE
Tagalog Localization #6-1

### PR DESCRIPTION
**Pull request by cordeta**
File : Html-questions.md
Location : Translations/Tagalog/questions/html-questions.md
Completion Rate : 100%
Word Count during present Translation : [864 WORDS]

### CODE REVIEW

**Comment by yangshun** [comment]
Hi @cordeta , thanks for all the hard work. I might not have been clear earlier, but it would be better to use a meaningful title for your PR because it eventually becomes the commit message. So instead of something like "Tagalog Localization #6-1", use "Tagalog Localization (HTML questions)" or something, that gives more context about the PR. It makes triaging the issues and commits easier later on. Many thanks!

**Review by yangshun — APPROVED** [review]

**Comment by cordeta** [comment]
Sure no problem . Now it's clearer :) Thank you also for the trust . Since I only have 1 more file left. Would you mind if i can help you to some of your projects too  @yangshun ?

**Comment by yangshun** [comment]
Do you mean other repositories?

**Comment by cordeta** [comment]
Yes , Exactly

**Comment by yangshun** [comment]
I don't think I have other projects at the moment that require translation.
Thanks a lot for your efforts though. You might want to look into
translating other projects, for example those by Facebook (:

**Comment by cordeta** [comment]
Yeah sure ;)

**Pull request merged**
