### PR TITLE
bengali translation added for javascript-questions

### PR DESCRIPTION
**Pull request by asifurrahaman754**
-  added a new folder called 'bn'(which is shorthand for Bengali) inside the website i18n folder. 
- I created a new file called "javascript-questions.md" and inside the file, 
- I translated the js question and answer into Bengali.  I added the translation until map vs for each section. I will add the rest later on. 
- Added a new element in the i18n array in docusaurus.config.js

### CODE REVIEW

**Review by yangshun — CHANGES_REQUESTED** [review]
Please remove the unrelated changes. You should only see have changes in the new Markdown file and `docusaurus.config.js`.

**Comment by asifurrahaman754** [comment]
Hey @yangshun can you please tell me what do you mean by new markdown file? And which file do i need to change to add a new translation?

**Comment by yangshun** [comment]
There are a bunch of formatting changes in files which shouldn't be touched for this PR, like the `SidebarAd.js` and `yarn.lock`.

Please separate out the "back to top" changes as another diff.

**Comment by asifurrahaman754** [comment]
Ok got it

**Comment by asifurrahaman754** [comment]
@yangshun then please close this pr. I'll make a another pr changing only the necessary file.

**Pull request closed without merging**
