### PR TITLE
Update Japanese: README.md to catch up

### PR DESCRIPTION
**Pull request by yhay81**
This is just catching up with current README.md.

(I forked repo into my account and made a pull request, but someone make branches on origin.
Which way is what you mean in contribution guide?)

### CODE REVIEW

**Comment by yangshun** [comment]
Both ways are fine. You can make a branch on origin or a branch on your own fork, but to merge it into master, it has go through a review process. I hope that makes sense.

**Comment by yhay81** [comment]
Thanks for comment and I see!
So, how to review the translation?
I think currently Japanese translator is only me.

**Comment by yangshun** [comment]
I trust that your translations are accurate, so we don't need other Japanese translators to approve it.

The review process is just to make sure that nothing blatantly wrong is done, like deleting the wrong files or changing stuff outside the translation. When you think this PR is ready to be merged, just add me as a reviewer.

**Comment by yhay81** [comment]
Okey!
I added you as a reviewer and thank you for merging!

**Comment by yangshun** [comment]
Thanks for the translations 👍

**Pull request merged**
