### PR TITLE
Add Chinese: update some of javascript questions

### PR DESCRIPTION
**Pull request by jeasonstudio**
Translate seven js-questions to Chinese.

### CODE REVIEW

**Comment by jeasonstudio** [comment]
@HaitianLiu please review.

**Comment by yangshun** [comment]
@jeasonstudio Why did you close it?

**Comment by jeasonstudio** [comment]
I changed the wrong file. To make the commit history clean, I reset, force push and close the old pr.

**Comment by yangshun** [comment]
You can simply force push to the same branch and it will be fine. When it is merged, the commits are squashed and rebased into one single commit so you don't have to worry about polluting history.

**Pull request closed without merging**
