### PR TITLE
html: Portuguese translation review HTML section

### PR DESCRIPTION
**Pull request by marianaWest**
I reviewed grammar and style for the HMTL question/answer section. I also updated the translation to include text that was present in English and Spanish versions but not in the Portuguese version.

### CODE REVIEW

**Comment by yangshun** [comment]
Thank you! Could you resolve the conflicts first before I can merge it? There's no need for the table of contents/index on each page now that I've made them automatically generated. You just have to remove it :)

**Comment by marianaWest** [comment]
Hi Yangshun, I removed the table of contents, I hope everything is fine now. Please let me know if there's any problems, this is my first open source contribution! Thank you for sharing your work.

**Review by yangshun — APPROVED** [review]
Thank you so much Mariana!

**Comment by marianaWest** [comment]
> Thank you so much Mariana!

Thank you for putting together this material! I'll try to review the CSS section in the near future, I'll let you know.

**Pull request merged**
